import React, { useEffect, useState, useCallback } from 'react';
import { View, FlatList, StyleSheet, RefreshControl } from 'react-native';
import {
  Text, FAB, Modal, Portal, TextInput, Button,
  Card, Chip, Snackbar, ActivityIndicator,
} from 'react-native-paper';
import api from '../../services/api';
import { DairyTheme } from '../../constants/Theme';

interface Samiti { id: number; name: string; code_4digit: string; }

export default function SamitisScreen() {
  const [samitis, setSamitis] = useState<Samiti[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [visible, setVisible] = useState(false);
  const [saving, setSaving] = useState(false);
  const [name, setName] = useState('');
  const [snackMsg, setSnackMsg] = useState('');

  const fetchSamitis = useCallback(async () => {
    try {
      const res = await api.get('/samitis');
      setSamitis(res.data);
    } catch { setSnackMsg('Failed to load samitis'); }
    finally { setLoading(false); setRefreshing(false); }
  }, []);

  useEffect(() => { fetchSamitis(); }, [fetchSamitis]);

  const handleAdd = async () => {
    if (!name.trim()) { setSnackMsg('Samiti name is required'); return; }
    try {
      setSaving(true);
      await api.post('/samitis', { name: name.trim() });
      setVisible(false);
      setName('');
      setSnackMsg('Samiti added!');
      fetchSamitis();
    } catch (e: any) {
      setSnackMsg(e.response?.data?.error || 'Failed to add samiti');
    } finally { setSaving(false); }
  };

  if (loading) return (
    <View style={styles.center}><ActivityIndicator size="large" color={DairyTheme.colors.primary} /></View>
  );

  return (
    <View style={styles.container}>
      <FlatList
        data={samitis}
        keyExtractor={item => String(item.id)}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); fetchSamitis(); }} />}
        contentContainerStyle={{ padding: 12 }}
        renderItem={({ item }) => (
          <Card style={styles.card}>
            <Card.Content style={styles.cardRow}>
              <View style={{ flex: 1 }}>
                <Text variant="titleMedium" style={{ fontWeight: 'bold' }}>{item.name}</Text>
                <Text variant="bodySmall" style={{ color: '#888', marginTop: 2 }}>ID: {item.id}</Text>
              </View>
              <Chip
                style={{ backgroundColor: DairyTheme.colors.primary }}
                textStyle={{ color: '#fff', fontSize: 18, fontWeight: 'bold', letterSpacing: 2 }}
              >
                {item.code_4digit}
              </Chip>
            </Card.Content>
          </Card>
        )}
        ListEmptyComponent={<Text style={styles.empty}>No samitis yet. Tap + to add one.</Text>}
      />

      <Portal>
        <Modal visible={visible} onDismiss={() => setVisible(false)} contentContainerStyle={styles.modal}>
          <Text variant="titleLarge" style={styles.modalTitle}>Add Samiti</Text>
          <Text variant="bodySmall" style={{ color: '#888', marginBottom: 16 }}>
            A unique 4-digit code will be auto-generated by the server.
          </Text>
          <TextInput
            label="Samiti Name"
            mode="outlined"
            value={name}
            onChangeText={setName}
            style={styles.input}
            autoFocus
          />
          <Button mode="contained" onPress={handleAdd} loading={saving} disabled={saving}>Add Samiti</Button>
          <Button onPress={() => setVisible(false)} style={{ marginTop: 8 }}>Cancel</Button>
        </Modal>
      </Portal>

      <FAB icon="plus" style={styles.fab} onPress={() => setVisible(true)} color="#fff" />
      <Snackbar visible={!!snackMsg} onDismiss={() => setSnackMsg('')} duration={3000}>{snackMsg}</Snackbar>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#F5F9FC' },
  center: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  card: { marginBottom: 10, borderRadius: 12, backgroundColor: '#fff' },
  cardRow: { flexDirection: 'row', alignItems: 'center' },
  empty: { textAlign: 'center', color: '#999', marginTop: 60 },
  fab: { position: 'absolute', right: 16, bottom: 24, backgroundColor: DairyTheme.colors.primary },
  modal: { backgroundColor: '#fff', margin: 20, padding: 24, borderRadius: 16 },
  modalTitle: { fontWeight: 'bold', marginBottom: 8 },
  input: { marginBottom: 16, backgroundColor: '#fff' },
});
